name: stylua
on: [push, pull_request]

jobs:
  stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JohnnyMorganz/stylua-action@v1.1.1
        with:
          token: ${{ secrets.GH_TOKEN }}
          args: --check --config-path=stylua.toml .
